// Generated by CoffeeScript 1.9.3
var terrain;

terrain = function(seed) {
  var instance;
  instance = Object.create(terrain.Terrain);
  instance.noise = new SimplexNoise(seed || Math.random);
  return instance;
};

terrain.Terrain = {
  _z: function(x, y) {
    var base, hills, mountains, roughness, z;
    z = 8;
    base = this.noise.noise2D(x / 250, y / 250);
    z += base * 10;
    mountains = base * this.noise.noise2D(x / 40, y / 40);
    z += mountains * 18;
    hills = Math.abs(base + mountains) * this.noise.noise2D(x / 10, y / 10);
    z += hills * 4;
    roughness = mountains * this.noise.noise2D(x / 2, y / 2);
    z += roughness * 2;
    if (z < 0) {
      z = 0;
    }
    return z;
  }
};
