// Generated by CoffeeScript 1.9.3
var landscape;

landscape = function(seed) {
  var instance;
  instance = Object.create(landscape.Landscape);
  instance.noise = new SimplexNoise(seed || Math.random);
  return instance;
};

landscape.Landscape = {
  height: function(x, y) {
    var base, edges, hills, mountains, roughness, z;
    z = 8;
    base = this.noise.noise2D(x / 250, y / 250);
    z += base * 10 - 2;
    mountains = this.noise.noise2D(x / 40, y / 40);
    z += base * mountains * 18;
    edges = Math.pow(mountains, 2);
    z += edges / 6;
    hills = Math.abs(base + mountains) * this.noise.noise2D(x / 10, y / 10);
    z += hills * 4;
    roughness = 1;
    roughness += 2 * mountains * this.noise.noise2D(x / 2, y / 2);
    z += roughness / (mountains < 0 ? 5 : 3);
    if (z < 0) {
      z = 0;
    }
    return z;
  },
  terrain: function(size) {
    var geometry, i, j, k, ref, ref1, x, y;
    size--;
    geometry = new THREE.PlaneGeometry(size, size, size, size);
    i = 0;
    for (x = j = 0, ref = size; 0 <= ref ? j <= ref : j >= ref; x = 0 <= ref ? ++j : --j) {
      for (y = k = 0, ref1 = size; 0 <= ref1 ? k <= ref1 : k >= ref1; y = 0 <= ref1 ? ++k : --k) {
        geometry.vertices[i].z = this.height(x, y);
        i++;
      }
    }
    geometry.computeFaceNormals();
    geometry.computeVertexNormals();
    return geometry;
  }
};
